export const FETCH_CHARACTERLIST_REQUEST = "FETCH_CHARACTERLIST_REQUEST"
export const FETCH_CHARACTERLIST_SUCCESS = "FETCH_CHARACTERLIST_SUCCESS"
export const FETCH_CHARACTERLIST_FAILURE = "FETCH_CHARACTERLIST_FAILURE"

export const FETCH_CHARACTER_REQUEST = "FETCH_CHARACTER_REQUEST"
export const FETCH_CHARACTER_SUCCESS = "FETCH_CHARACTER_SUCCESS"
export const FETCH_CHARACTER_FAILURE = "FETCH_CHARACTER_FAILURE"