export const FETCH_CHARACTERLIST_REQUEST = "FETCH_CHARACTERLIST_REQUEST"
export const FETCH_CHARACTERLIST_SUCCESS = "FETCH_CHARACTERLIST_SUCCESS"
export const FETCH_CHARACTERLIST_FAILURE = "FETCH_CHARACTERLIST_FAILURE"